name: BattlePassRevive
version: '${project.version}'
main: org.vaylorm.battlePassRevive.BattlePassRevive
api-version: '1.20'
commands:
  battlepass:
    description: Основная команда BattlePass
    aliases: [bp]
    usage: /<command> [claim|claimreward|...]
permissions:
  battlepass.admin:
    description: Доступ к админским командам BattlePass
    default: op
