name: BattlePassRevive
version: '${project.version}'
main: org.vaylorm.battlePassRevive.BattlePassRevive
api-version: '1.20'
commands:
  battlepass:
    description: Основная команда BattlePass
    aliases:
      - bp
      - quests
    usage: |
      §c/battlepass - Показать помощь
      §c/battlepass restart <quest_id> - Перезапустить квест
permissions:
  battlepass.admin:
    description: Доступ к админским командам BattlePass
    default: op
